### ISSUE TITLE
Update package request

### ISSUE THREAD

**Issue by joelhy** [slimphp/Slim-Http#10]
Could you please update slim/http package to latest version of slimphp?
It's been almost half year since last commit of Slim-Http. And https://github.com/slimphp/Slim got lots of goodies into it. I am planning to use Slim-Http in my homebake framework. It would be great to have Slim-Http with all updates from Slimphp. Looking forward to it, and thanks in advance.

**Comment by akrabat** [comment]
@joelhy I'll see what I can do. 

Note that it's likely that there will be significant changes before stable on this repo as we're going to use it as the base for 4.0.

**Comment by joelhy** [comment]
Noted.

**Comment by joelhy** [comment]
I have already switch to base my homebake framework on zend-diactoros.
IMHO, it's better for Slim v4.0 to based on diactoros, and improve diactoros, rather than improve slim-php package.
PHP community will benefit through the collaboration.
