### ISSUE TITLE
New tagged release

### ISSUE THREAD

**Issue by SlvrEagle23** [slimphp/Slim-Http#103]
Hello Slim maintainer team!

We're making use of the new Slim Framework 4.x alongside Slim-Http, and in particular we've needed to take advantage of a few of the changes that have been made in the last few months since the last tagged release back in May.

I was curious if there is a roadmap for the next tagged release, or if another one can be dropped in by the team, just so we're not sitting on `dev-master`, which always gives me a sketchy feeling deep inside.

If there's anything we outsider folks can do to help contribute toward that end, let me know as well. Happy to help. :)

**Comment by l0gicgate** [comment]
Hey @SlvrEagle23 I will tag a release tonight here. I think the milestone is pretty full. I will close this issue once I do!

**Comment by l0gicgate** [comment]
Here you go @SlvrEagle23 

https://github.com/slimphp/Slim-Http/releases/tag/0.8

**Comment by SlvrEagle23** [comment]
@l0gicgate Thank you!!

**Comment by SlvrEagle23** [comment]
@l0gicgate Is Packagist not auto-updating from GH? Not sure if that's a manual process for you guys.

**Comment by l0gicgate** [comment]
@SlvrEagle23 just manually refreshed, should be good now. I have to setup the github hooks

**Comment by SlvrEagle23** [comment]
@l0gicgate Excellent, thank you again :D
