### ISSUE TITLE
PHPUnit 8 required by php-http/psr7-integration-tests

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Http#107]
Composer notified me about the following problem.

> php-http/psr7-integration-tests dev-master requires phpunit/phpunit ^8.0

Should we update PHPUnit to 8.0? If so, we need also `php ^7.2`.

**Comment by l0gicgate** [comment]
Yes. We need to do this for all repos.

**Comment by l0gicgate** [comment]
We also need to do this:

https://github.com/slimphp/Slim/pull/2908
