### ISSUE TITLE
 Slim\Http\Uri do not implements static method 'createFromGlobals'

### ISSUE THREAD

**Issue by jockchou** [slimphp/Slim-Http#11]
```
$uri = Uri::createFromGlobals($globals);
```

in request.php line 179, but `Slim\Http\Uri` do not implements static method 'createFromGlobals'

**Comment by tiepnguyen** [comment]
I'm having the same issue, have you got solution?

**Comment by gsouf** [comment]
First we need to know if this package is aimed to be maintained. @codeguy  ?

**Comment by damianopetrungaro** [comment]
At the moment the Uri implements the [createFromGlobals method](https://github.com/slimphp/Slim-Http/blob/master/src/Uri.php#L158-L210).

This package is current under development, and is maintained (as you can see the 0.2 has been released today).
