### ISSUE TITLE
Accessing Route Arguments In middleware 

### ISSUE THREAD

**Issue by nixoncode** [slimphp/Slim-Http#139]
An Invokable class middleware has the  following signature

```php
__invoke(ServerRequest $request, RequestHandlerInterface $handler)
```
is there an easier way of accessing the route parameters? Right now I have the below code

```php
// returns Slim\Routing\RoutingResults obj
$routingResult = $request->getAttribute('__routingResults__');
        
$key = $routingResult->getRouteArguments()['key'];
```

Previously I could do something like `$key = $request->getAttribute('key')`

**Comment by l0gicgate** [comment]
Use the `RouteContext` object first of all. 

```php
$routeContext = RouteContext::fromRequest($request);
```

And the `getRouteArguments()` method is correct. 

I don’t quite understand what you’re saying though about `$request->getAttribute(‘key’)`. That functionality is provided by the PSR-7 implementation and is doing as it should. It has nothing to do with route arguments tho.

**Comment by nixoncode** [comment]
Thanks much better.
ignore my last statement about `$request->getAttribute(‘key’)`. 

I think this should be mentioned somewhere in the docs

**Comment by l0gicgate** [comment]
It is in the docs https://www.slimframework.com/docs/v4/cookbook/retrieving-current-route.html
