### ISSUE TITLE
Possibility of removing final on constructors?

### ISSUE THREAD

**Issue by dlundgren** [slimphp/Slim-Http#146]
The following classes had constructors that were converted to `final` in #118, and it'd be nice to not have them final for those of us who are extending the classes, and modifying the constructors.

- ServerRequest
- Response
- URI

I'm particularly interested in `Response` as I extend it to create a Redirect class that I use to more easily handle forwards (internal framework), and actual redirects.

**Comment by l0gicgate** [comment]
Remove them and run static analysis, you’ll understand why we shouldn’t.
