### ISSUE TITLE
[Discussion] Status Code as Constants

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim-Http#40]
Related: https://github.com/slimphp/Slim/issues/2310

**Comment by akrabat** [comment]
See https://github.com/php-fig/http-message-util/blob/master/src/StatusCodeInterface.php

Related to #62

**Comment by mathmarques** [comment]
Shouldn't we use the StatusCode class added on 3.11? https://github.com/slimphp/Slim/pull/2429

**Comment by akrabat** [comment]
> Shouldn't we use the StatusCode class added on 3.11? https://github.com/slimphp/Slim/pull/2429

Or should we have used the FIG ones in 3.11?

**Comment by akrabat** [comment]
Migrated to https://github.com/slimphp/Slim-Psr7/issues/8
