### ISSUE TITLE
ReasonPhrase not passed to withStatus when using withJson in Response.php

### ISSUE THREAD

**Issue by adjenks** [slimphp/Slim-Http#45]
Self explanatory title I'd say.

**Comment by juffalow** [comment]
I don't know I get it right, but this works for me:

```
return $response->withJson([ 'test' => 'test'])->withStatus(200, 'Whatever');
```

```
Request URL: http://localhost/
Request Method: GET
Status Code: 200 Whatever
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade
```

**Comment by adjenks** [comment]
It's been too long and I don't even remember why I wanted this.
If that works, then great. I think I was expecting to be able to write:
`return $response->withJson([ 'test' => 'test'], 200, 'Whatever');`
Or something of the sort. It's fine, it's all fine... Just ignore me... Hahaha.
