### ISSUE TITLE
Move Non PSR7 Methods to Decorator

### ISSUE THREAD

**Issue by johnrobertporter** [slimphp/Slim-Http#50]
I would like to suggest we make a pure PSR7 implementation and move any non-PSR7 methods to a decorator classes labelled something like `SlimRequestDecorator`.

Any of the immutable methods should of course clone properly down through the involved classes.

This would allow us to create pure PSR objects if needed, and add functionality like non-PSR methods and our static factory methods and media type parsers within the decorator.

Feedback on this suggestion would be appreciated.

**Comment by johnrobertporter** [comment]
Ok, I think an interface of the Slim methods would be beneficial at least; one that extends the Psr interface to aid in type declaration.

**Comment by akrabat** [comment]
Done. #67
