### ISSUE TITLE
Update to require >= PHP 7.0.0

### ISSUE THREAD

**Issue by dbtlr** [slimphp/Slim-Http#58]
With Slim 4 requiring support for PHP 7.0.0, it would be good to update the minimum requirement for Slim-Http as well.

Not only will this provide similar benefits here, but it will allow us to integrate the PSR-17 spec properly, which has a minimum requirement as well: https://packagist.org/packages/psr/http-factory

**Comment by akrabat** [comment]
Yes please.

We can improve the type hinting that way too.
