### ISSUE TITLE
Remove Headers from FactoryInterface?

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim-Http#6]
Should Headers be a requirement in our FactoryInterface? Headers are purely internal to the request and do not have their own PSR7 interface. We can still use our own Headers implementation, but we'll keep it as an implementation detail of the Request class.

**Comment by geggleto** [comment]
Can we not hide those details inside the factory?

**Comment by codeguy** [comment]
@akrabat Your thoughts?

**Comment by akrabat** [comment]
I'd like it to be an implementation detail.
