### ISSUE TITLE
Ensure headers are consistent

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Http#61]
* Ensure that our headers implementation is completely compliant with PSR-7
* Ensure that `getHeader()` and `getHeaders()` are consistent. See https://github.com/slimphp/Slim/issues/2400

**Comment by akrabat** [comment]
If I do `$message = $message->withHeader('Content-Type', 'text/plain');` and then `$message->getHeaders().`, I'd expect the array key to be `Content-Type`, not `content-type`.

**Comment by 1ma** [comment]
> With that being said, the implementation of getHeaders() should preserve the original case but no mention of preserving the HTTP_ prefix is in the spec.

Please, don't  keep the HTTP_ prefix. This would break one of my libraries that strongly depends on strict PSR-7 compliance. I actually got involved in the past to fix this issue in `slim/http` (https://github.com/slimphp/Slim/issues/2091).

**Comment by akrabat** [comment]
Yes, I agree completely with losing the HTTP prefix and the underscores when reading from the environment.

**Comment by geggleto** [comment]
I am with @akrabat what you put in should be what you get out. Can't say i have ever seen headers with the underscore tho.

**Comment by l0gicgate** [comment]
Okay so I guess someone has to make a choice here. Case sensitivity either matters across the board or it does not. That's the only way to achieve consistent output.

`getHeader()` is case insensitive. The input of `withHeader()` should not determine the output of `getHeader()` or `getHeaders()`.

Consistent output should not depend on inconsistent input. That's just my 2 cents. @akrabat you can have the final say, I'm not sure what to do here.

**Comment by llvdl** [comment]
I would also prefer normalized header names, but apparently some HTTP clients do not treat header names as case insensitive and therefore PSR-7 dictates that `getHeaders()` returns the original case. 

I suggest following PSR-7 and make a best effort with the request headers:

* the header that is given with `withHeader`, `getHeader` and `withAddedHeader` should be normalized when comparing headers, but the original case should be stored for use with `getHeaders`.
* use the `getallheaders` polyfill as suggested by @l0gicgate to get the original header names, which falls back to `$_SERVER`
* if `$_SERVER` is used to fetch the headers, the `HTTP_` prefix should be dropped as it is not part of the actual header name. Also underscores should be converted to hyphens.

I am unsure what to do with the normalization of underscores and hyphens in header names. It seems like hyphens are converted to underscores in `$_SERVER`. So the header name may then end up as `my_header` or `my-header`, depending on the web server used. It is probably an edge case, so I suggest not converting hyphens to underscores before comparing.

**Comment by akrabat** [comment]
[RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) states that header names are HT (Hyphen Text) and so do no have underscores in them.

**Comment by l0gicgate** [comment]
@akrabat okay so `getHeaders()` will provide whatever the original output of the `getallheaders()` function returns? If so, that will all be `ucword()` case.

Define what you mean by normalized output and which method returns that.

**Comment by akrabat** [comment]
Migrated to https://github.com/slimphp/Slim-Psr7/issues/11
