### ISSUE TITLE
slim-http or slim

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim-Http#8]
Hello,
I'm working on a curated list of psr7 related project.
I'm not sure if I should consider this project or only Slim.

What is the plan here ?
Is this project the psr7 implementation of slim ? If yes why it is not a dependency ?

I can imagine that I'm not the first one who ask the question but I didn't find the answer...

**Comment by JoeBengalen** [comment]
I think the plan is to use this one in Slim v4. Cannot change now because it would be a BC break.
