### ISSUE TITLE
Type of $default can be more than string

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Http#85]
The docblock defines the second param `$default` to be `string`. But actually it can be `null` as well. By the way, couldn't that param be of any type, i.e. `mixed`?

https://github.com/slimphp/Slim-Http/blob/473a81173018e19e18c78e31d221e51973a6d199/src/ServerRequest.php#L530-L555

**Comment by l0gicgate** [comment]
In what case could that param be anything but a string?

**Comment by adriansuter** [comment]
I guess I thought so, because the `@return` is `mixed`. Is it possible, that `$default` might be an array too?

**Comment by l0gicgate** [comment]
I think it should return a string only. Parsed `$_POST` or `$_GET` params should always be strings.. unless there's some weird case where the value is overwritten by the user to be something else which would be weird.

**Comment by adriansuter** [comment]
Then this issue can be closed.
